package Form;

import Entity.NHANVIEN;
import Model.NHANVIENDAO;
import TienIch.MsgBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nguye
 */
public class CHANGE_PASS extends javax.swing.JFrame {

    NHANVIENDAO nvdao = new NHANVIENDAO();
    boolean hide1 = false;
    boolean hide2 = false;

    /**
     * Creates new form doimatkhau
     */
    public CHANGE_PASS() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnMK = new javax.swing.JButton();
        btnNLMK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNLMK = new javax.swing.JPasswordField();
        txtMk = new javax.swing.JPasswordField();
        txtMkMs = new javax.swing.JPasswordField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("                                                                               THAY ĐỔI TÀI KHOẢN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NHẬP LẠI MẬT KHẨU MỚI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 150, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("MẬT KHẨU MỚI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, 28));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 320, 30));

        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 100, 37));

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 90, 37));

        btnMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/showpass.png"))); // NOI18N
        btnMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 42, 29));

        btnNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/showpass.png"))); // NOI18N
        btnNLMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNLMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 42, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("MẬT KHẨU CŨ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 28));
        getContentPane().add(txtNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 320, 30));
        getContentPane().add(txtMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 320, 30));
        getContentPane().add(txtMkMs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 320, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/55.jpg"))); // NOI18N
        BG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMKActionPerformed
        hide1 = !hide1;
        if (hide1) {
            txtMkMs.setEchoChar((char) 0);
        } else {
            txtMkMs.setEchoChar('*');
        }
    }//GEN-LAST:event_btnMKActionPerformed

    private void btnNLMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNLMKActionPerformed
        hide2 = !hide2;
        if (hide2) {
            txtNLMK.setEchoChar((char) 0);
        } else {
            txtNLMK.setEchoChar('*');
        }
    }//GEN-LAST:event_btnNLMKActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        xacNhan();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        openLogin();
    }//GEN-LAST:event_btnCancelActionPerformed

    void xacNhan() {
        if (check()) {
            String maNV = txtUsername.getText().trim();
            String mk = txtMk.getText();
            String mkM = txtMkMs.getText();
            String nlmk = txtNLMK.getText();
            NHANVIEN nv = nvdao.selectById(maNV);
            if (nv != null) {
                if (nv.getPass().equalsIgnoreCase(mk)) {
                    if(mkM.equalsIgnoreCase(nlmk)){
                        nv.setPass(mkM);
                        nvdao.update(nv);
                        clear();
                        MsgBox.alert(this, "Đổi mật khẩu thành công!");
                    }
                    else {
                        MsgBox.alert(this, "Xác nhận mật khẩu chưa đúng!");
                    }
                } else {
                    MsgBox.alert(this, "Sai mật khẩu!");
                }
            } else {
                MsgBox.alert(this, "Sai tên đăng nhập!");
            }
        }
    }

    boolean check() {
        if (txtUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên tài khoản!");
            txtUsername.requestFocus();
            return false;
        } else if (txtMk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password!");
            txtMk.requestFocus();
            return false;
        } else if (txtMkMs.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password mới!");
            txtMkMs.requestFocus();
            return false;
        } else if (txtNLMK.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cần xác nhận lại password!");
            txtNLMK.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    
    void openLogin(){
        LOGIN lg = new LOGIN(true);
        lg.setVisible(true);
        dispose();
    }
    
    void clear(){
        txtUsername.setText("");
        txtMk.setText("");
        txtMkMs.setText("");
        txtNLMK.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHANGE_PASS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMK;
    private javax.swing.JButton btnNLMK;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtMk;
    private javax.swing.JPasswordField txtMkMs;
    private javax.swing.JPasswordField txtNLMK;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
