/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.LICHLAM;
import Entity.NHANVIEN;
import Model.LICHLAMDAO;
import Model.NHANVIENDAO;
import TienIch.Auth;
import TienIch.MsgBox;
import TienIch.XDate;
import TienIch.XImage;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class DIEMDANH extends javax.swing.JFrame {

    LICHLAMDAO lldao = new LICHLAMDAO();
    List<LICHLAM> listDD = new ArrayList();

    /**
     * Creates new form DIEMDANH
     */
    public DIEMDANH() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(this);
    }

    public DIEMDANH(NHANVIEN nv) {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(this);
        Auth.user=nv;
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDD = new javax.swing.JTable();
        btnNop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblDD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nv", "Tên", "Ca", "Điểm danh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDD);
        if (tblDD.getColumnModel().getColumnCount() > 0) {
            tblDD.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblDD.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblDD.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        btnNop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNop.setText("NỘP");
        btnNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("DANH SÁCH LÀM HÔM NAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnNop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(btnNop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopActionPerformed
        nopDiemDanh();
    }//GEN-LAST:event_btnNopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    void fillTable() {
        NHANVIENDAO nvdao = new NHANVIENDAO();
        DefaultTableModel model = (DefaultTableModel) tblDD.getModel();
        model.setRowCount(0);
        listDD.clear();
        Date lichNgay = XDate.toDate(getToday(), "MM/dd/yyyy");
        List<LICHLAM> list = lldao.selectBangSchedule(lichNgay);
        listDD = lldao.selectBangSchedule(lichNgay);
        for (LICHLAM l : list) {
            NHANVIEN nv = nvdao.selectById(l.getIdNV());
            model.addRow(new Object[]{
                l.getIdNV(), nv.getTenNV(), l.getCa(), l.isDiemDanh()
            });
        }
    }

    String getToday() {
        Calendar c = Calendar.getInstance();
        int thang = c.get(Calendar.MONTH)+1;
        int ngay = c.get(Calendar.DATE);
        int nam = c.get(Calendar.YEAR);
        String date = thang + "/" + ngay + "/" + nam;
        return date;
    }
    
    void nopDiemDanh(){
        for(int i=0;i<tblDD.getRowCount();i++){
            listDD.get(i).setDiemDanh(Boolean.parseBoolean(tblDD.getValueAt(i, 3).toString()));
            lldao.update(listDD.get(i));
        }
        MsgBox.alert(null, "Đã điểm danh xong");
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIEMDANH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIEMDANH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIEMDANH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIEMDANH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIEMDANH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDD;
    // End of variables declaration//GEN-END:variables
}
