/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.DANHSACHMON;
import Model.DANHSACHMONDAO;
import Model.HOADONCTDAO;
import TienIch.MsgBox;
import TienIch.XImage;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.text.DecimalFormat;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LENOVO
 */
public class FOOD_MENU extends javax.swing.JFrame {

    DANHSACHMONDAO dsmdao = new DANHSACHMONDAO();
    HOADONCTDAO hdctdao = new HOADONCTDAO();
    int row = 0;

    /**
     * Creates new form QLNV
     */
    public FOOD_MENU() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(this);
        filltable();
        lblHinhAnh.setToolTipText("noimage2.jpg");
        lblHinhAnh.setIcon(XImage.read("noimage2.jpg"));
        if (tblDSM.getRowCount() > 0) {
            edit();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        rboThucAn = new javax.swing.JRadioButton();
        rboNuocUong = new javax.swing.JRadioButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMaMon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDSM = new javax.swing.JTable();
        btnExportDCD = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THỰC ĐƠN CỦA QUÁN");
        setResizable(false);

        tab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Đơn giá:");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên món:");

        txtTenMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Loại:");

        lblHinhAnh.setBackground(new java.awt.Color(0, 153, 153));
        lblHinhAnh.setOpaque(true);
        lblHinhAnh.setPreferredSize(new java.awt.Dimension(150, 150));

        btnChonAnh.setText("CHOOSE AVATAR");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        rboThucAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rboThucAn.setText("Thức ăn");
        rboThucAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboThucAnActionPerformed(evt);
            }
        });

        rboNuocUong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rboNuocUong.setText("Nước uống");
        rboNuocUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboNuocUongActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_NHANVIEN/last.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_NHANVIEN/lui.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_NHANVIEN/tien.png"))); // NOI18N
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_NHANVIEN/fist.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtTim.setForeground(new java.awt.Color(204, 204, 204));
        txtTim.setText("Nhập tên món cần tìm");
        txtTim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimFocusLost(evt);
            }
        });
        txtTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTimMousePressed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconSearch.jpg"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã món:");

        lblMaMon.setBackground(new java.awt.Color(255, 255, 255));
        lblMaMon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMaMon.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThem)
                        .addGap(10, 10, 10)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel1))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rboThucAn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rboNuocUong))
                                    .addComponent(lblMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonAnh)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnFirst)
                .addGap(95, 95, 95)
                .addComponent(btnPre)
                .addGap(88, 88, 88)
                .addComponent(btnNext)
                .addGap(79, 79, 79)
                .addComponent(btnLast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnChonAnh)
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addComponent(jSeparator6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboThucAn)
                            .addComponent(rboNuocUong)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnFirst)
                    .addComponent(btnPre)
                    .addComponent(btnLast))
                .addGap(40, 40, 40))
        );

        tab.addTab("Chi tiết món", jPanel1);

        tblDSM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món", "Tên món", "Loại", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDSM);

        btnExportDCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNutExportExcel.png"))); // NOI18N
        btnExportDCD.setText("EXPORT TO EXCEL");
        btnExportDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDCDActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconNutXemTatCaChuyenDe.png"))); // NOI18N
        jButton1.setText("XEM TẤT CẢ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportDCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportDCD)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        tab.addTab("Danh sách món ăn", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rboThucAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboThucAnActionPerformed
        rboThucAn.setSelected(true);
        rboNuocUong.setSelected(false);
    }//GEN-LAST:event_rboThucAnActionPerformed

    private void rboNuocUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboNuocUongActionPerformed
        rboThucAn.setSelected(false);
        rboNuocUong.setSelected(true);
    }//GEN-LAST:event_rboNuocUongActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        ChonHinhAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void tblDSMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMMouseClicked
        row = tblDSM.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblDSMMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtTimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusLost
        if (txtTim.getText().trim().equalsIgnoreCase("")) {
            txtTim.setText("Nhập tên món cần tìm");
            txtTim.setFont(new Font("Tahoma", Font.ITALIC, 12));
            txtTim.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtTimFocusLost

    private void txtTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimMouseClicked
        if (txtTim.getForeground() != Color.black) {
            txtTim.setText("");
            txtTim.setFont(new Font("Tahoma", Font.PLAIN, 12));
            txtTim.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTimMouseClicked

    private void txtTimMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimMousePressed
        if (txtTim.getForeground() != Color.black) {
            txtTim.setText("");
            txtTim.setFont(new Font("Tahoma", Font.PLAIN, 12));
            txtTim.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtTimMousePressed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        search();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnExportDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDCDActionPerformed
        export();
    }//GEN-LAST:event_btnExportDCDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        row = 0;
        filltable();
        edit();
    }//GEN-LAST:event_jButton1ActionPerformed

    void insert() {
        if (check()) {
            DANHSACHMON dsm = getForm();
            dsmdao.insert(dsm);
            filltable();
            clear();
            MsgBox.alert(tab, "Thêm món thành công!");
        }
    }

    void update() {
        if (lblMaMon.getText().trim().isEmpty()) {
            MsgBox.alert(tab, "Chọn món cần cập nhật!");
        } else {
            if (check()) {
                DANHSACHMON dsm = getForm();
                dsm.setIdMon(Integer.parseInt(lblMaMon.getText()));
                dsmdao.update(dsm);
                filltable();
                MsgBox.alert(tab, "Cập nhật thành công!");
            }
        }
    }

    void delete() {
        if (lblMaMon.getText().isEmpty()) {
            MsgBox.alert(tab, "Chọn món cần xóa!");
        } else {
            if (MsgBox.confirm(tab, "Bạn có chắc muốn xóa món này?")) {
                hdctdao.deleteTheoMon(Integer.parseInt(lblMaMon.getText()));
                dsmdao.delete(Integer.parseInt(lblMaMon.getText()));
                filltable();
                clear();
                MsgBox.alert(tab, "Đã xóa thành công!");
            }
        }
    }

    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblDSM.getModel();
        model.setRowCount(0);
        List<DANHSACHMON> list = dsmdao.selectAll();
        if (list.size() > 0) {
            for (DANHSACHMON dsm : list) {
                Object[] row = {dsm.getIdMon(), dsm.getTenMon(), dsm.isLoai() ? "Thức ăn" : "Nước uống", dsm.getDonGia()
                };
                model.addRow(row);
            }
        }
    }

    void clear() {
        lblMaMon.setText("");
        txtTenMon.setText("");
        txtGia.setText("");
        rboThucAn.setSelected(false);
        rboNuocUong.setSelected(false);
        lblHinhAnh.setToolTipText("noimage2.jpg");
        lblHinhAnh.setIcon(XImage.read("noimage2.jpg"));
        txtTenMon.requestFocus();
    }

    boolean check() {
        if (txtTenMon.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập tên món!");
            return false;
        } else if (!rboThucAn.isSelected() && !rboNuocUong.isSelected()) {
            MsgBox.alert(this, "Chưa chọn loại món!");
            return false;
        } else if (txtGia.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập giá!");
            return false;
        } else if (!txtGia.getText().trim().matches("\\d+")) {
            MsgBox.alert(this, "Giá phải là số!");
            return false;
        } else {
            return true;
        }
    }

    DANHSACHMON getForm() {
        DANHSACHMON dsm = new DANHSACHMON();
        dsm.setTenMon(txtTenMon.getText().trim());
        if (rboThucAn.isSelected()) {
            dsm.setLoai(true);
        }
        if (rboNuocUong.isSelected()) {
            dsm.setLoai(false);
        }
        dsm.setDonGia(Double.parseDouble(txtGia.getText().trim()));
        dsm.setHinhanh(lblHinhAnh.getToolTipText());
        return dsm;
    }

    void setForm(DANHSACHMON dsm) {
        lblMaMon.setText(String.valueOf(dsm.getIdMon()));
        txtTenMon.setText(dsm.getTenMon());
        if (dsm.isLoai()) {
            rboThucAn.setSelected(true);
            rboNuocUong.setSelected(false);
        } else {
            rboThucAn.setSelected(false);
            rboNuocUong.setSelected(true);
        }
        txtGia.setText(String.valueOf((int) dsm.getDonGia()));
        try {
            Image img = this.read(dsm.getHinhanh());
            Image resizedImage = img.getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH);
            lblHinhAnh.setIcon(new ImageIcon(resizedImage));
            lblHinhAnh.setToolTipText(dsm.getHinhanh());
        } catch (Exception e) {
        }
    }

    public Image read(String file) {
        File f = new File("logos", file);
        try {
            Image img = ImageIO.read(f);
            return img;
        } catch (Exception ex) {

        }
        return null;
    }

    void edit() {
        int idMon = Integer.parseInt(tblDSM.getValueAt(row, 0).toString());
        DANHSACHMON dsm = dsmdao.selectById(idMon);
        this.setForm(dsm);
        tblDSM.setRowSelectionInterval(row, row);
        tab.setSelectedIndex(0);
    }

    public void ChonHinhAnh() {
        JFileChooser jf = new JFileChooser("src\\imgFood\\");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("image", "jpg", "png", "gif");
        jf.setFileFilter(filter);
        jf.setMultiSelectionEnabled(false);

        int x = jf.showDialog(this, "Chọn ảnh");
        if (x == jf.APPROVE_OPTION) {
            File f = jf.getSelectedFile();
            XImage.save(f);
            try {
                Image img = ImageIO.read(f);
                Image resizedImage = img.getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH);
                lblHinhAnh.setIcon(new ImageIcon(resizedImage));
                lblHinhAnh.setToolTipText(f.getName());
            } catch (Exception e) {
            }
        } else {
            return;
        }
    }

    void search() {
        DefaultTableModel model = (DefaultTableModel) tblDSM.getModel();
        model.setRowCount(0);
        String ndTim = txtTim.getText().trim();
        List<DANHSACHMON> list = dsmdao.selectAll();
        String[] str = null;
        boolean tim = false;
        int count = 0;
        if (txtTim.getForeground() == Color.black) {
            str = ndTim.split(" ");
            tim = true;
        }
        for (int i = 0; i < list.size(); i++) {
            if (tim && ndTim.equalsIgnoreCase(list.get(i).getTenMon())) {
                setForm(list.get(i));
                model.addRow(new Object[]{
                    list.get(i).getIdMon(), list.get(i).getTenMon(), list.get(i).isLoai() ? "Thức ăn" : "Nước uống", list.get(i).getDonGia()
                });
                row = i;
                tblDSM.setRowSelectionInterval(row, row);
                count ++;
                break;
            } else if (tim) {
                for (int j = 0; j < str.length; j++) {
                    if (list.get(i).getTenMon().toLowerCase().contains(str[j].toLowerCase())) {
                        count --;
                        model.addRow(new Object[]{
                            list.get(i).getIdMon(), list.get(i).getTenMon(), list.get(i).isLoai() ? "Thức ăn" : "Nước uống", list.get(i).getDonGia()
                        });
                        row = tblDSM.getRowCount()-1;
                        setForm(list.get(i));
                    }
                }
            }
        }
        if (count == 0) {
            filltable();
            MsgBox.alert(tab, "Không tìm thấy món!");
        } else if(count == 1) {
            MsgBox.alert(tab, "Đã tìm thấy món!");
        }
        else{
            MsgBox.alert(tab, "Có thể bạn tìm các món này!");
        }
    }
    
    void export(){
        JFileChooser jf = new JFileChooser("src\\Excel");
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jf.setMultiSelectionEnabled(false);
        
        int x = jf.showDialog(this, "Export");
        if (x == jf.APPROVE_OPTION) {
            File f = new File(jf.getSelectedFile().getAbsolutePath()+("\\Danh sách món ăn.xls"));
            toExcel(tblDSM, f);
            MsgBox.alert(this, "Xuất file Excel thành công");
        }
    }

    void toExcel(JTable table, File file) {
        try {
            TableModel model = table.getModel();
            FileWriter excel = new FileWriter(file);

            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i) + "\t");
            }

            excel.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString() + "\t");
                }
                excel.write("\n");
            }

            excel.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void first() {
        if (tblDSM.getRowCount() > 0) {
            this.row = 0;
            this.edit();
        }
    }

    void next() {
        if (tblDSM.getRowCount() > 0) {
            if (this.row < tblDSM.getRowCount() - 1) {
                this.row++;
                this.edit();
            } else {
                MsgBox.alert(this, "Đã ở cuối danh sách!");
            }
        }
    }

    void prev() {
        if (tblDSM.getRowCount() > 0) {
            if (this.row > 0) {
                this.row--;
                this.edit();
            } else {
                MsgBox.alert(this, "Đã ở đầu danh sách!");
            }
        }

    }

    void last() {
        if (tblDSM.getRowCount() > 0) {
            this.row = tblDSM.getRowCount() - 1;
            this.edit();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FOOD_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FOOD_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FOOD_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FOOD_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FOOD_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnExportDCD;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblMaMon;
    private javax.swing.JRadioButton rboNuocUong;
    private javax.swing.JRadioButton rboThucAn;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblDSM;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
