/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.NHANVIEN;
import TienIch.Auth;
import TienIch.MsgBox;
import TienIch.XImage;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author TOSHIBA
 */
public class HOME extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Home
     */
    public HOME() {
        initComponents();
        init();
    }

    public HOME(NHANVIEN nv) {
        initComponents();
        init();
        Auth.user = nv;
        try {
            Image img = this.read(nv.getAvatar());
            Image resizedImage = img.getScaledInstance(lblAvtNV.getWidth(), lblAvtNV.getHeight(), Image.SCALE_SMOOTH);
            lblAvtNV.setIcon(new ImageIcon(resizedImage));
            lblAvtNV.setToolTipText(nv.getAvatar());
        } catch (Exception e) {
        }
        if (nv.getVaiTro().equalsIgnoreCase("NHÂN VIÊN")) {
            btnOrder.setVisible(false);
            btnHoaDon.setVisible(false);
            btnNV.setVisible(false);
            btnTD.setVisible(false);
            btnThongKe.setVisible(false);
            btnBan.setVisible(false);
            mnDiemDanh.setVisible(false);
            mnThongKe.setVisible(false);
            lblHienThi.setText("Nhân viên: "+nv.getIdNV());
        } else if (nv.getVaiTro().equalsIgnoreCase("THU NGÂN")) {
            btnNV.setVisible(false);
            btnTD.setVisible(false);
            btnThongKe.setVisible(false);
            btnBan.setVisible(false);
            mnDiemDanh.setVisible(false);
            lblHienThi.setText("Thu ngân: "+nv.getIdNV());
        }
        else{
            lblHienThi.setText("Quản lí: "+nv.getIdNV());
            btnOrder.setVisible(false);
            mnDKLam.setVisible(false);
        }
    }
    
    public Image read(String file) {
        File f = new File("logos", file);
        try {
            Image img = ImageIO.read(f);
            return img;
        } catch (Exception ex) {

        }
        return null;
    }
    
    void init(){
        this.setIconImage(XImage.getAppIcon());
        lblAvtNV.setIcon(XImage.read("noimage.jpg"));
        setLocationRelativeTo(this);
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnLichLam = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnNV = new javax.swing.JButton();
        btnBan = new javax.swing.JButton();
        btnTD = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnThoát = new javax.swing.JButton();
        lblDongHo = new javax.swing.JLabel();
        lblAvtNV = new javax.swing.JLabel();
        lblHienThi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homeBG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDangXuat = new javax.swing.JMenuItem();
        mnDMK = new javax.swing.JMenuItem();
        mnError = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnXemLich = new javax.swing.JMenuItem();
        mnDKLam = new javax.swing.JMenuItem();
        mnDiemDanh = new javax.swing.JMenuItem();
        mnThongKe = new javax.swing.JMenu();
        mnMonAn = new javax.swing.JMenuItem();
        mnDT = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Đang xuat.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnLichLam.setBackground(new java.awt.Color(255, 255, 255));
        btnLichLam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLichLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lịch làm.png"))); // NOI18N
        btnLichLam.setText("Lịch làm");
        btnLichLam.setFocusable(false);
        btnLichLam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichLam.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLichLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichLamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLichLam);

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/order.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setFocusable(false);
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOrder);

        btnHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open.png"))); // NOI18N
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHoaDon);

        btnNV.setBackground(new java.awt.Color(255, 255, 255));
        btnNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhân viên.png"))); // NOI18N
        btnNV.setText("Nhân viên");
        btnNV.setFocusable(false);
        btnNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNV);

        btnBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bàn.png"))); // NOI18N
        btnBan.setText("Bàn");
        btnBan.setFocusable(false);
        btnBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBan);

        btnTD.setBackground(new java.awt.Color(255, 255, 255));
        btnTD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thực đơn.png"))); // NOI18N
        btnTD.setText("Thực đơn");
        btnTD.setFocusable(false);
        btnTD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTD);

        btnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thống kê.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        btnThoát.setBackground(new java.awt.Color(255, 255, 255));
        btnThoát.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoát.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btnThoát.setText("Thoát");
        btnThoát.setFocusable(false);
        btnThoát.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoát.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoátActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoát);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 59));

        lblDongHo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 51));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setText("10:10:10 PM");
        getContentPane().add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 120, 40));

        lblAvtNV.setBackground(new java.awt.Color(51, 51, 255));
        lblAvtNV.setOpaque(true);
        getContentPane().add(lblAvtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 60, 60));

        lblHienThi.setBackground(new java.awt.Color(204, 204, 204));
        lblHienThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHienThi.setForeground(new java.awt.Color(51, 0, 255));
        lblHienThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHienThi.setText("Nhân viên: NV1");
        lblHienThi.setOpaque(true);
        getContentPane().add(lblHienThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 110, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Hệ THỐNG QUẢN LÝ QUÁN ĂN ĐỈNH CAO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 520, 120));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("AMAZING GOOD JOB !!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 260, 30));

        homeBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/homeBG1.jpg"))); // NOI18N
        getContentPane().add(homeBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 470));

        jMenu1.setText("Hệ thống");

        mnDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnDangXuat.setText("Đăng xuất");
        mnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnDangXuat);

        mnDMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnDMK.setText("Đổi mật khẩu");
        mnDMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDMKActionPerformed(evt);
            }
        });
        jMenu1.add(mnDMK);

        mnError.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnError.setText("Liên hệ");
        mnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnErrorActionPerformed(evt);
            }
        });
        jMenu1.add(mnError);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lịch làm");

        mnXemLich.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnXemLich.setText("Xem lịch làm");
        mnXemLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXemLichActionPerformed(evt);
            }
        });
        jMenu2.add(mnXemLich);

        mnDKLam.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnDKLam.setText("Đăng kí làm");
        mnDKLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDKLamActionPerformed(evt);
            }
        });
        jMenu2.add(mnDKLam);

        mnDiemDanh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mnDiemDanh.setText("Điểm danh");
        mnDiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemDanhActionPerformed(evt);
            }
        });
        jMenu2.add(mnDiemDanh);

        jMenuBar1.add(jMenu2);

        mnThongKe.setText("Thống kê");

        mnMonAn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        mnMonAn.setText("Món ăn");
        mnMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMonAnActionPerformed(evt);
            }
        });
        mnThongKe.add(mnMonAn);

        mnDT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        mnDT.setText("Doanh thu");
        mnDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDTActionPerformed(evt);
            }
        });
        mnThongKe.add(mnDT);

        jMenuBar1.add(mnThongKe);

        jMenu5.setText("Help");

        jMenu9.setText("Hướng dẫn sử dụng");
        jMenu5.add(jMenu9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoátActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoátActionPerformed

    private void btnLichLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichLamActionPerformed
        openLichLam();
    }//GEN-LAST:event_btnLichLamActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        openLogin();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        openNV();
    }//GEN-LAST:event_btnNVActionPerformed

    private void btnTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDActionPerformed
        openDSM();
    }//GEN-LAST:event_btnTDActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        openBan();
    }//GEN-LAST:event_btnBanActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
       openOrder();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void mnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangXuatActionPerformed
        openLogin();
    }//GEN-LAST:event_mnDangXuatActionPerformed

    private void mnDMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDMKActionPerformed
        MsgBox.alert(this, "Chức năng chưa hoàn thành");
    }//GEN-LAST:event_mnDMKActionPerformed

    private void mnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnErrorActionPerformed
        openError();
    }//GEN-LAST:event_mnErrorActionPerformed

    private void mnXemLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXemLichActionPerformed
        openXemLich();
    }//GEN-LAST:event_mnXemLichActionPerformed

    private void mnDKLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDKLamActionPerformed
        openDkLam();
    }//GEN-LAST:event_mnDKLamActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        openBill();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void mnDiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemDanhActionPerformed
        openDiemDanh();
    }//GEN-LAST:event_mnDiemDanhActionPerformed

    private void mnMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMonAnActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mnMonAnActionPerformed

    private void mnDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDTActionPerformed
        openThongKe(1);
    }//GEN-LAST:event_mnDTActionPerformed

    void openLogin(){
        boolean kt = MsgBox.confirm(this, "Bạn muốn đăng xuất");
        if (kt) {
            LOGIN l = new LOGIN(true);
            this.setVisible(false);
            l.setVisible(true);
            Auth.clear();
        }
    }
    
    void openLichLam(){
        SCHEDULE sch = new SCHEDULE(Auth.user);
        sch.setVisible(true);
    }
    
    void openNV(){
        EMPLOYEE e = new EMPLOYEE(Auth.user);
        e.setVisible(true);
    }
    
    void openDSM(){
        FOOD_MENU f = new FOOD_MENU();
        f.setVisible(true);
    }
    
    void openBan(){
        TABLE t = new TABLE();
        t.setVisible(true);
    }
    
    void openOrder(){
        ORDER or = new ORDER(Auth.user);
        or.setVisible(true);
    }
    
    void openBill(){
        BILL b = new BILL();
        b.setVisible(true);
    }
    
    void openThongKe(int i){
        THONGKE tk = new THONGKE();
        tk.setVisible(true);
        tk.selectTab(i);
    }
    
    void openDiemDanh(){
        DIEMDANH dd = new DIEMDANH(Auth.user);
        dd.setVisible(true);
    }
    
    void openError(){
        CONTRACT_US se = new CONTRACT_US();
        se.setVisible(true);
    }
    
    void openXemLich(){
        SCHEDULE sc = new SCHEDULE(Auth.user);
        sc.setVisible(true);
    }
    
    void openDkLam(){
        DKILICH dkl = new DKILICH(Auth.user);
        dkl.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnLichLam;
    private javax.swing.JButton btnNV;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnTD;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThoát;
    private javax.swing.JLabel homeBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAvtNV;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHienThi;
    private javax.swing.JMenuItem mnDKLam;
    private javax.swing.JMenuItem mnDMK;
    private javax.swing.JMenuItem mnDT;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenuItem mnDiemDanh;
    private javax.swing.JMenuItem mnError;
    private javax.swing.JMenuItem mnMonAn;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenuItem mnXemLich;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                Date now = new Date();
                SimpleDateFormat f = new SimpleDateFormat();

                f.applyPattern("hh:mm:ss aa");

                String time = f.format(now);
                lblDongHo.setText(time);
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
    }
}
