/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.BAN;
import Model.BANDAO;
import Model.BANSUDUNGDAO;
import Model.THONGKEDAO;
import TienIch.MsgBox;
import TienIch.XImage;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class TABLE extends javax.swing.JFrame {

    BANDAO bdao = new BANDAO();
    BANSUDUNGDAO bsddao = new BANSUDUNGDAO();
    int row = 0;
    THONGKEDAO dao = new THONGKEDAO();

    /**
     * Creates new form QLNV
     */
    public TABLE() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(this);
        filltable();
        if(tblBan.getRowCount()>0){
            edit();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTenBan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        rboTangTret = new javax.swing.JRadioButton();
        rboLau = new javax.swing.JRadioButton();
        rboSanVuon = new javax.swing.JRadioButton();
        btnBan = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("                                                                                    BÀN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Vị trí:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(txtTenBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 147, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 40));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, 40));

        tblBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Tên bàn", "Vị trí", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 604, 230));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên bàn:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        rboTangTret.setText("Tầng trệt");
        rboTangTret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboTangTretActionPerformed(evt);
            }
        });
        getContentPane().add(rboTangTret, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        rboLau.setText("Lầu 1");
        rboLau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboLauActionPerformed(evt);
            }
        });
        getContentPane().add(rboLau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        rboSanVuon.setText("Sân vườn");
        rboSanVuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboSanVuonActionPerformed(evt);
            }
        });
        getContentPane().add(rboSanVuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
        getContentPane().add(btnBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 160, 170));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        btnNew.setText("Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, 40));
        getContentPane().add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 70, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/55.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rboTangTretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboTangTretActionPerformed
        rboTangTret.setSelected(true);
        rboSanVuon.setSelected(false);
        rboLau.setSelected(false);
    }//GEN-LAST:event_rboTangTretActionPerformed

    private void rboLauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboLauActionPerformed
        rboTangTret.setSelected(false);
        rboSanVuon.setSelected(false);
        rboLau.setSelected(true);
    }//GEN-LAST:event_rboLauActionPerformed

    private void rboSanVuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboSanVuonActionPerformed
        rboTangTret.setSelected(false);
        rboSanVuon.setSelected(true);
        rboLau.setSelected(false);
    }//GEN-LAST:event_rboSanVuonActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanMouseClicked
        row = tblBan.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblBanMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        timkey();
    }//GEN-LAST:event_jButton1ActionPerformed

    void timkey() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblBan.getModel();
            model.setRowCount(0);
            String keyword = txtTim.getText();
            List<Object[]> list = dao.TimtheokeyTB(keyword);
            for (Object[] row : list) {
                model.addRow(row);
            }

        } catch (Exception e) {
        }}
    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblBan.getModel();
        model.setRowCount(0);
        try {
            List<BAN> list = bdao.selectAll();
            for (BAN b : list) {
                Object[] row = {b.getIdBan(), b.getTenBan(), b.getVitri(), b.getTrangthai()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    void insert() {
        if (check()) {
            BAN b = getForm();
            bdao.insert(b);
            clear();
            filltable();
            MsgBox.alert(this, "Thêm bàn thành công!");
        }
    }

    void update() {
        int row = tblBan.getSelectedRow();
        if (row > 0) {
            MsgBox.alert(this, "Chọn bàn cần cập nhật!");
        } else {
            if (check()) {
                int idBan = Integer.parseInt(tblBan.getValueAt(row, 0).toString());
                BAN b = getForm();
                b.setIdBan(idBan);
                bdao.update(b);
                filltable();
                MsgBox.alert(this, "Cập nhật thành công!");
            }
        }

    }

    void delete() {
        int row = tblBan.getSelectedRow();
        if (tblBan.getRowCount() <= 0) {
            MsgBox.alert(this, "Chưa có bàn để xóa!");
        } else if (row < 0) {
            MsgBox.alert(this, "Chọn bàn cần xóa!");
        } else {
            if (MsgBox.confirm(this, "Bạn có chắc muốn xóa bàn này?")) {
                int idBan = Integer.parseInt(tblBan.getValueAt(row, 0).toString());
                bsddao.delete(idBan);
                bdao.delete(idBan);
                filltable();
                clear();
                MsgBox.alert(this, "Đã xóa thành công!");
            }
        }
    }

    boolean check() {
        if (txtTenBan.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Chưa nhập tên bàn!");
            return false;
        } else if (!rboLau.isSelected() && !rboSanVuon.isSelected() && !rboTangTret.isSelected()) {
            MsgBox.alert(this, "Chưa chọn vị trí!");
            return false;
        } else {
            return true;
        }
    }

    BAN getForm() {
        BAN b = new BAN();
        b.setTenBan(txtTenBan.getText().trim());
        if (rboLau.isSelected()) {
            b.setVitri(rboLau.getText());
        } else if (rboSanVuon.isSelected()) {
            b.setVitri(rboSanVuon.getText());
        } else if (rboTangTret.isSelected()) {
            b.setVitri(rboTangTret.getText());
        }
        return b;
    }

    void setForm(BAN b) {
        txtTenBan.setText(b.getTenBan());
        if (b.getVitri().equalsIgnoreCase(rboLau.getText())) {
            rboLau.setSelected(true);
            rboSanVuon.setSelected(false);
            rboTangTret.setSelected(false);
        } else if (b.getVitri().equalsIgnoreCase(rboSanVuon.getText())) {
            rboLau.setSelected(false);
            rboSanVuon.setSelected(true);
            rboTangTret.setSelected(false);
        } else {
            rboLau.setSelected(false);
            rboSanVuon.setSelected(false);
            rboTangTret.setSelected(true);
        }
        btnBan.setText("BÀN " + b.getIdBan() + " " + b.getTrangthai());
        if (b.getTrangthai().equalsIgnoreCase("Trống")) {
            btnBan.setBackground(new Color(240, 240, 240));
            btnBan.setForeground(Color.BLACK);
        } else {
            btnBan.setBackground(Color.BLUE);
            btnBan.setForeground(Color.WHITE);
        }
    }

    void clear() {
        txtTenBan.setText("");
        rboLau.setSelected(false);
        rboSanVuon.setSelected(false);
        rboTangTret.setSelected(false);
        btnBan.setText("");
        btnBan.setBackground(new Color(240, 240, 240));
    }

    void edit() {
        int idBan = Integer.parseInt(tblBan.getValueAt(row, 0).toString());
        BAN b = bdao.selectById(idBan);
        this.setForm(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TABLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rboLau;
    private javax.swing.JRadioButton rboSanVuon;
    private javax.swing.JRadioButton rboTangTret;
    private javax.swing.JTable tblBan;
    private javax.swing.JTextField txtTenBan;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
